title: Vinícius Nazato
logo: "/imgs/profile.png?raw=true"
theme: jekyll-theme-minimal

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Welcome to my portfolio page!
  <br><br>
  My name is Vinícius Nazato, a passionate data scientist with a curiosity for solving complex problems using data-driven approaches.
  <br><br>
  Contact me to talk about the specifics of my projects.
  <br><br>
  <a href="https://www.linkedin.com/in/vinicius-nazato/">View my LinkedIn profile</a
